// react/react-demo/src/FullName.jsx
import React, { useState, useEffect } from "react";

function FullName() {
  console.log("React FullName component re-rendered"); // Log re-render

  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [fullName, setFullName] = useState("");

  // Update fullName when firstName or lastName changes
  useEffect(() => {
    setFullName(`${firstName} ${lastName}`);
  }, [firstName, lastName]);

  return (
    <div>
      <input
        type="text"
        placeholder="First Name"
        value={firstName}
        onChange={(e) => setFirstName(e.target.value)}
      />
      <input
        type="text"
        placeholder="Last Name"
        value={lastName}
        onChange={(e) => setLastName(e.target.value)}
      />
      <p>Full Name: {fullName}</p>
    </div>
  );
}

export default FullName;

// solid/solid_demo/src/FullName.jsx
import { createSignal, createEffect } from "solid-js";

function FullName() {
  const [firstName, setFirstName] = createSignal("");
  const [lastName, setLastName] = createSignal("");

  // Derived fullName
  const fullName = () => `${firstName()} ${lastName()}`;

  // Log when firstName, lastName or fullName updates
  createEffect(() => {
    console.log("Solid.js: firstName or lastName updated");
    console.log("Solid.js: Full Name is now:", fullName());
  });

  return (
    <div>
      <input
        type="text"
        placeholder="First Name"
        value={firstName()}
        onInput={(e) => setFirstName(e.target.value)}
      />
      <input
        type="text"
        placeholder="Last Name"
        value={lastName()}
        onInput={(e) => setLastName(e.target.value)}
      />
      <p>Full Name: {fullName()}</p>
    </div>
  );
}

export default FullName;
